// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Content/Bounties.tsx";
import * as $$$$$$1 from "./sections/Content/BountiesCard.tsx";
import * as $$$$$$2 from "./sections/Content/Cards.tsx";
import * as $$$$$$3 from "./sections/Content/Cta.tsx";
import * as $$$$$$4 from "./sections/Content/Faq.tsx";
import * as $$$$$$5 from "./sections/Content/Hero.tsx";
import * as $$$$$$6 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$14 from "./sections/decoads.tsx";
import * as $$$$$$7 from "./sections/Footer.tsx";
import * as $$$$$$8 from "./sections/Footer/Footer.tsx";
import * as $$$$$$9 from "./sections/Header/Header.tsx";
import * as $$$$$$10 from "./sections/HomeUS.tsx";
import * as $$$$$$11 from "./sections/ItWorks.tsx";
import * as $$$$$$15 from "./sections/join.tsx";
import * as $$$$$$16 from "./sections/prices.tsx";
import * as $$$$$$12 from "./sections/PricesUS.tsx";
import * as $$$$$$17 from "./sections/signup.tsx";
import * as $$$$$$13 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Content/Bounties.tsx": $$$$$$0,
    "site/sections/Content/BountiesCard.tsx": $$$$$$1,
    "site/sections/Content/Cards.tsx": $$$$$$2,
    "site/sections/Content/Cta.tsx": $$$$$$3,
    "site/sections/Content/Faq.tsx": $$$$$$4,
    "site/sections/Content/Hero.tsx": $$$$$$5,
    "site/sections/Content/Testimonials.tsx": $$$$$$6,
    "site/sections/decoads.tsx": $$$$$$14,
    "site/sections/Footer.tsx": $$$$$$7,
    "site/sections/Footer/Footer.tsx": $$$$$$8,
    "site/sections/Header/Header.tsx": $$$$$$9,
    "site/sections/HomeUS.tsx": $$$$$$10,
    "site/sections/ItWorks.tsx": $$$$$$11,
    "site/sections/join.tsx": $$$$$$15,
    "site/sections/prices.tsx": $$$$$$16,
    "site/sections/PricesUS.tsx": $$$$$$12,
    "site/sections/signup.tsx": $$$$$$17,
    "site/sections/Theme/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
